name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check node version
        run: node -v
      - name: Check npm version
        run: npm -v
      - run: npm install
      - name: Give permission to jest
        run: chmod +x ./node_modules/.bin/jest
      - name: Run tests
        run: npx jest
